import {useEffect,useState} from 'react';
import {toast} from 'react-toastify';
import api,{dataOf} from '../services/api';

export default function AppointmentsPage(){
 const[children,setChildren]=useState([]),[clinics,setClinics]=useState([]),[items,setItems]=useState([]),[form,setForm]=useState({childId:'',clinicId:'',appointmentDate:'',appointmentTime:'09:00',notes:''});
 const load=()=>api.get('/appointments').then(r=>setItems(dataOf(r)));
 useEffect(()=>{Promise.all([api.get('/children'),api.get('/clinics')]).then(([a,b])=>{const childList=dataOf(a),clinicList=dataOf(b),selected=sessionStorage.getItem('selectedClinicId');setChildren(childList);setClinics(clinicList);setForm(f=>({...f,childId:childList[0]?.id||'',clinicId:selected&&clinicList.some(c=>String(c.id)===selected)?selected:clinicList[0]?.id||''}));sessionStorage.removeItem('selectedClinicId')});load()},[]);
 const book=async e=>{e.preventDefault();try{await api.post('/appointments',{...form,childId:Number(form.childId),clinicId:Number(form.clinicId),appointmentTime:form.appointmentTime.length===5?form.appointmentTime+':00':form.appointmentTime});toast.success('Appointment booked successfully');setForm(x=>({...x,appointmentDate:'',notes:''}));load()}catch(x){toast.error(x.response?.data?.message||'Unable to book appointment')}};
 const cancel=async id=>{try{await api.patch(`/appointments/${id}/status`,{status:'CANCELLED'});toast.success('Appointment cancelled');load()}catch(x){toast.error(x.response?.data?.message||'Unable to cancel')}};
 return <div><div><h2 className="page-title">Appointments</h2><p className="page-subtitle">Book and manage clinic appointments.</p></div><div className="mt-6 grid gap-6 xl:grid-cols-[390px_1fr]"><form className="card h-fit" onSubmit={book}><div className="grid h-14 w-14 place-items-center rounded-3xl bg-gradient-to-br from-teal-500 to-blue-600 text-2xl text-white">◷</div><h3 className="mt-4 section-title">Book appointment</h3><div className="mt-5 space-y-4"><label className="text-sm font-bold text-slate-600">Child<select className="input mt-2" value={form.childId} onChange={e=>setForm({...form,childId:e.target.value})}>{children.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="text-sm font-bold text-slate-600">Clinic<select className="input mt-2" value={form.clinicId} onChange={e=>setForm({...form,clinicId:e.target.value})}>{clinics.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="text-sm font-bold text-slate-600">Date<input className="input mt-2" type="date" min={new Date(Date.now()+86400000).toISOString().slice(0,10)} value={form.appointmentDate} onChange={e=>setForm({...form,appointmentDate:e.target.value})} required/></label><label className="text-sm font-bold text-slate-600">Time<input className="input mt-2" type="time" value={form.appointmentTime} onChange={e=>setForm({...form,appointmentTime:e.target.value})} required/></label><label className="text-sm font-bold text-slate-600">Notes<textarea className="input mt-2 min-h-24" value={form.notes} placeholder="Additional notes (optional)" onChange={e=>setForm({...form,notes:e.target.value})}/></label><button className="btn-primary w-full">Book appointment</button></div></form><div><h3 className="section-title">Appointment history</h3><div className="mt-4 grid gap-4 lg:grid-cols-2">{items.map(a=><article className="card card-hover" key={a.id}><div className="flex items-start justify-between gap-3"><div><span className={`badge ${a.status==='COMPLETED'?'bg-emerald-50 text-emerald-700':a.status==='CANCELLED'||a.status==='REJECTED'?'bg-red-50 text-red-700':'bg-blue-50 text-blue-700'}`}>{a.status}</span><h4 className="mt-3 font-extrabold text-slate-900">{a.childName}</h4><p className="mt-1 text-sm text-slate-500">{a.clinicName}</p></div><div className="rounded-2xl bg-slate-50 px-3 py-2 text-center"><p className="text-sm font-black text-slate-900">{a.appointmentDate}</p><p className="text-xs text-slate-500">{a.appointmentTime}</p></div></div>{a.notes&&<p className="mt-4 rounded-2xl bg-slate-50 p-3 text-sm text-slate-600">{a.notes}</p>}{['BOOKED','ACCEPTED'].includes(a.status)&&<button className="btn-danger mt-4" onClick={()=>cancel(a.id)}>Cancel appointment</button>}</article>)}{!items.length&&<div className="card text-slate-500">No appointments found.</div>}</div></div></div></div>;
}
