import {useState} from 'react';
import {toast} from 'react-toastify';
import api,{dataOf} from '../services/api';

const suggestions=['Which vaccines are due at 6 weeks?','What should I do after my baby gets a vaccine?','My child missed a vaccine dose. What happens next?','Which vaccine side effects need urgent care?'];

export default function ChatbotPage(){
 const[messages,setMessages]=useState([{from:'bot',text:'Hello. I can help with childhood vaccination schedules, missed doses, side effects, appointment preparation, and after-care.'}]),[text,setText]=useState(''),[loading,setLoading]=useState(false);
 const send=async(value)=>{const question=(value??text).trim();if(!question)return;setMessages(x=>[...x,{from:'user',text:question}]);setText('');setLoading(true);try{const response=dataOf(await api.post('/chatbot',{message:question}));setMessages(x=>[...x,{from:'bot',text:response.answer}])}catch(x){toast.error(x.response?.data?.message||'Vaccination assistant is currently unavailable')}finally{setLoading(false)}};
 return <div className="mx-auto max-w-5xl"><div className="mb-6"><h2 className="page-title">Vaccination Assistant</h2><p className="page-subtitle">Ask questions about vaccination schedules, missed doses, side effects, and after-care.</p></div><div className="overflow-hidden rounded-[34px] border border-slate-200 bg-white shadow-[0_24px_70px_rgba(15,23,42,.10)]"><div className="flex items-center justify-between bg-gradient-to-r from-slate-950 via-teal-950 to-blue-950 px-6 py-5 text-white"><div className="flex items-center gap-3"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-white/10 text-2xl">✦</div><div><p className="font-black">Vaccination Assistant</p><p className="text-xs text-teal-200">Vaccination information and guidance</p></div></div><span className="badge bg-emerald-400/15 text-emerald-200">Available</span></div><div className="scrollbar-thin h-[520px] overflow-y-auto bg-gradient-to-b from-slate-50 to-white p-4 sm:p-6"><div className="space-y-5">{messages.map((m,i)=><div key={i} className={`flex ${m.from==='user'?'justify-end':'justify-start'}`}><div className={`max-w-[88%] whitespace-pre-wrap rounded-3xl px-5 py-4 text-sm leading-7 shadow-sm sm:max-w-[78%] ${m.from==='user'?'rounded-br-md bg-gradient-to-r from-teal-600 to-blue-600 text-white':'rounded-bl-md border border-slate-200 bg-white text-slate-700'}`}>{m.text}</div></div>)}{loading&&<div className="flex justify-start"><div className="rounded-3xl rounded-bl-md border border-slate-200 bg-white px-5 py-4 text-sm text-slate-500">Preparing your response…</div></div>}</div></div><div className="border-t border-slate-200 bg-white p-4 sm:p-5"><div className="mb-4 flex flex-wrap gap-2">{suggestions.map(s=><button key={s} className="rounded-full border border-slate-200 bg-slate-50 px-3 py-2 text-xs font-semibold text-slate-600 hover:border-teal-300 hover:bg-teal-50" onClick={()=>send(s)}>{s}</button>)}</div><form className="flex gap-3" onSubmit={e=>{e.preventDefault();send()}}><textarea className="input min-h-14 resize-none" value={text} onChange={e=>setText(e.target.value)} placeholder="Ask a vaccination question"/><button className="btn-primary self-end" disabled={loading}>Send</button></form><p className="mt-3 text-xs text-slate-400">For general information only. Consult a pediatrician for medical advice or emergencies.</p></div></div></div>;
}
