import {useEffect,useState} from 'react';
import {toast} from 'react-toastify';
import api,{dataOf} from '../../services/api';
import {OpenStreetMapPicker} from '../../components/OpenStreetMap';

export default function ClinicDashboard(){
 const[apps,setApps]=useState([]),[query,setQuery]=useState(''),[children,setChildren]=useState([]),[report,setReport]=useState(null),[selected,setSelected]=useState(null),[schedule,setSchedule]=useState([]),[profile,setProfile]=useState(null);
 const load=()=>{api.get('/appointments').then(r=>setApps(dataOf(r)));api.get('/reports/clinic',{params:{period:'monthly'}}).then(r=>setReport(dataOf(r)));api.get('/clinics/profile').then(r=>setProfile(dataOf(r)))};
 useEffect(()=>{load()},[]);
 const run=async(fn,message)=>{try{await fn();toast.success(message);load()}catch(x){toast.error(x.response?.data?.message||'Operation failed')}};
 const status=(id,value)=>run(()=>api.patch(`/appointments/${id}/status`,{status:value}),'Appointment updated');
 const search=()=>api.get('/children/search',{params:{query}}).then(r=>setChildren(dataOf(r)));
 const openChild=async child=>{setSelected(child);setSchedule(dataOf(await api.get(`/vaccinations/child/${child.id}`)))};
 const updateVaccine=async(row,value)=>{try{await api.put(`/vaccinations/child/${selected.id}`,{vaccineId:row.vaccineId,status:value,completedDate:value==='COMPLETED'?new Date().toISOString().slice(0,10):null,notes:`Updated by clinic: ${value}`});toast.success('Vaccination status updated');openChild(selected)}catch(x){toast.error(x.response?.data?.message||'Unable to update')}};
 const saveProfile=e=>{e.preventDefault();if(profile.latitude==null||profile.longitude==null)return toast.error('Select clinic location on the map');run(()=>api.put('/clinics/profile',profile),'Clinic profile updated')};
 return <div><div><h2 className="page-title">Clinic Dashboard</h2><p className="page-subtitle">Manage appointments, vaccination records, reports, and clinic details.</p></div>{report&&<div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[['Completed',report.completedVaccinations],['Pending',report.pendingVaccinations],['Appointments',report.appointments],['Vaccinated children',report.vaccinatedChildren]].map(([name,value])=><div className="stat-card" key={name}><p className="text-sm font-bold text-slate-500">{name}</p><p className="mt-2 text-4xl font-black text-slate-950">{value}</p></div>)}</div>}
 <div className="mt-7 grid gap-6 xl:grid-cols-2"><section><h3 className="section-title">Appointment management</h3><div className="mt-3 space-y-3">{apps.map(a=><article className="card" key={a.id}><div className="flex justify-between gap-3"><div><h4 className="font-extrabold">{a.childName}</h4><p className="text-sm text-slate-500">{a.appointmentDate} at {a.appointmentTime}</p></div><span className="badge h-fit bg-slate-100 text-slate-700">{a.status}</span></div>{a.status==='BOOKED'&&<div className="mt-4 flex gap-2"><button className="btn-primary py-2" onClick={()=>status(a.id,'ACCEPTED')}>Accept</button><button className="btn-danger" onClick={()=>status(a.id,'REJECTED')}>Reject</button></div>}{a.status==='ACCEPTED'&&<button className="btn-primary mt-4 py-2" onClick={()=>status(a.id,'COMPLETED')}>Complete appointment</button>}</article>)}</div></section><section><h3 className="section-title">Search child</h3><div className="mt-3 flex gap-2"><input className="input" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Child, parent or child ID"/><button className="btn-primary" onClick={search}>Search</button></div><div className="mt-3 space-y-2">{children.map(c=><button className="card card-hover w-full text-left" key={c.id} onClick={()=>openChild(c)}><h4 className="font-extrabold">#{c.id} {c.name}</h4><p className="text-sm text-slate-500">Parent: {c.parentName} · DOB: {c.dateOfBirth}</p></button>)}</div></section></div>
 {selected&&<section className="mt-7"><h3 className="section-title">Vaccination record · {selected.name}</h3><div className="mt-3 overflow-x-auto rounded-3xl border border-slate-200 bg-white shadow-sm"><table className="w-full text-left"><thead className="bg-slate-950 text-white"><tr><th className="p-4">Vaccine</th><th>Dose</th><th>Due</th><th>Status</th><th className="p-4">Update</th></tr></thead><tbody>{schedule.map(r=><tr className="border-t border-slate-100" key={r.vaccineId}><td className="p-4 font-bold">{r.vaccineName}</td><td>{r.doseNumber}</td><td>{r.dueDate}</td><td><span className="badge bg-slate-100">{r.status}</span></td><td className="p-4"><div className="flex flex-wrap gap-2">{r.status!=='COMPLETED'&&<button className="font-bold text-emerald-700" onClick={()=>updateVaccine(r,'COMPLETED')}>Complete</button>}<button className="font-bold text-amber-700" onClick={()=>updateVaccine(r,'PENDING')}>Pending</button><button className="font-bold text-red-700" onClick={()=>updateVaccine(r,'MISSED')}>Missed</button></div></td></tr>)}</tbody></table></div></section>}
 </div>;
}
