import {useEffect,useState} from 'react';
import {toast} from 'react-toastify';
import api,{dataOf} from '../../services/api';
import {OpenStreetMapPicker} from '../../components/OpenStreetMap';

const clinicInit={name:'',email:'',phone:'',address:'',city:'Pune',latitude:null,longitude:null,active:true};

export default function AdminDashboard(){
 const[parents,setParents]=useState([]),[children,setChildren]=useState([]),[clinics,setClinics]=useState([]),[query,setQuery]=useState(''),[verified,setVerified]=useState(''),[clinicForm,setClinicForm]=useState(clinicInit),[editClinicId,setEditClinicId]=useState(null);
 const load=async()=>{const params={query:query||undefined,verified:verified===''?undefined:verified==='true'};const[a,b,c]=await Promise.all([api.get('/users/parents',{params:{query:query||undefined}}),api.get('/children/search',{params:{query}}),api.get('/clinics/all',{params})]);setParents(dataOf(a));setChildren(dataOf(b));setClinics(dataOf(c))};
 useEffect(()=>{load()},[]);
 const run=async(fn,message)=>{try{await fn();toast.success(message);await load()}catch(x){toast.error(x.response?.data?.message||'Operation failed')}};
 const saveClinic=async e=>{e.preventDefault();if(clinicForm.latitude==null||clinicForm.longitude==null)return toast.error('Select clinic location on the map');await run(()=>editClinicId?api.put(`/clinics/${editClinicId}`,clinicForm):api.post('/clinics',clinicForm),editClinicId?'Clinic updated':'Clinic added');setClinicForm(clinicInit);setEditClinicId(null)};
 const editParent=p=>{const firstName=prompt('First name',p.firstName);if(firstName===null)return;const lastName=prompt('Last name',p.lastName);if(lastName===null)return;const phone=prompt('Phone',p.phone);if(phone===null)return;run(()=>api.put(`/users/parents/${p.id}`,{...p,firstName,lastName,phone}),'Parent updated')};
 const editChild=c=>{const name=prompt('Child name',c.name);if(name===null)return;run(()=>api.put(`/children/${c.id}`,{name,dateOfBirth:c.dateOfBirth,gender:c.gender,bloodGroup:c.bloodGroup||'UNKNOWN',medicalNotes:c.medicalNotes}),'Child updated')};
 return <div><div><h2 className="page-title">Admin Dashboard</h2><p className="page-subtitle">Manage parent, child, and clinic records.</p></div><div className="mt-6 grid gap-4 sm:grid-cols-3">{[['Parents',parents.length,'♙'],['Children',children.length,'☆'],['Clinics',clinics.length,'✚']].map(([name,value,icon])=><div className="stat-card" key={name}><div className="text-2xl">{icon}</div><p className="mt-4 text-sm font-bold text-slate-500">{name}</p><p className="text-4xl font-black text-slate-950">{value}</p></div>)}</div><div className="card mt-6 flex flex-wrap gap-3"><input className="input max-w-lg" placeholder="Search by name, city, email, or ID" value={query} onChange={e=>setQuery(e.target.value)}/><select className="input max-w-xs" value={verified} onChange={e=>setVerified(e.target.value)}><option value="">All clinic statuses</option><option value="true">Verified</option><option value="false">Unverified</option></select><button className="btn-primary" onClick={load}>Search</button></div>
 <div className="mt-7 grid gap-6 xl:grid-cols-2"><section><h3 className="section-title">Parent management</h3><div className="mt-3 space-y-3">{parents.map(p=><article className="card" key={p.id}><div className="flex justify-between gap-3"><div><h4 className="font-extrabold">{p.firstName} {p.lastName}</h4><p className="text-sm text-slate-500">{p.email} · {p.phone}</p><p className="mt-1 text-xs text-slate-500">{p.city||'City not set'} · {p.active?'Active':'Inactive'}</p></div><span className={`badge h-fit ${p.active?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-500'}`}>{p.active?'ACTIVE':'INACTIVE'}</span></div><div className="mt-4 flex flex-wrap gap-2"><button className="btn-secondary" onClick={()=>editParent(p)}>Edit</button><button className="btn-secondary" onClick={()=>run(()=>api.patch(`/users/${p.id}/active`,null,{params:{value:!p.active}}),'Account status updated')}>{p.active?'Deactivate':'Activate'}</button><button className="btn-danger" onClick={()=>confirm('Delete parent and related data?')&&run(()=>api.delete(`/users/parents/${p.id}`),'Parent deleted')}>Delete</button></div></article>)}</div></section><section><h3 className="section-title">Child management</h3><div className="mt-3 space-y-3">{children.map(c=><article className="card" key={c.id}><h4 className="font-extrabold">#{c.id} {c.name}</h4><p className="text-sm text-slate-500">Parent: {c.parentName} · DOB: {c.dateOfBirth}</p><div className="mt-4 flex gap-2"><button className="btn-secondary" onClick={()=>editChild(c)}>Edit</button><button className="btn-danger" onClick={()=>confirm('Delete child?')&&run(()=>api.delete(`/children/${c.id}`),'Child deleted')}>Delete</button></div></article>)}</div></section></div>
 <section className="mt-8 grid gap-6 xl:grid-cols-[.9fr_1.1fr]"><form className="card h-fit" onSubmit={saveClinic}><div className="flex items-center justify-between"><div><h3 className="section-title">{editClinicId?'Update clinic':'Add clinic'}</h3><p className="text-sm text-slate-500">Select the clinic location on the map.</p></div>{editClinicId&&<button type="button" className="btn-secondary" onClick={()=>{setEditClinicId(null);setClinicForm(clinicInit)}}>Cancel</button>}</div><div className="mt-5 grid gap-3 sm:grid-cols-2"><input className="input" placeholder="Clinic name" value={clinicForm.name} required onChange={e=>setClinicForm({...clinicForm,name:e.target.value})}/><input className="input" type="email" placeholder="Email" value={clinicForm.email} required onChange={e=>setClinicForm({...clinicForm,email:e.target.value})}/><input className="input" placeholder="Phone" value={clinicForm.phone} required onChange={e=>setClinicForm({...clinicForm,phone:e.target.value})}/><input className="input" placeholder="City" value={clinicForm.city} required onChange={e=>setClinicForm({...clinicForm,city:e.target.value})}/><textarea className="input min-h-24 sm:col-span-2" placeholder="Address" value={clinicForm.address} required onChange={e=>setClinicForm({...clinicForm,address:e.target.value})}/><div className="sm:col-span-2"><OpenStreetMapPicker latitude={clinicForm.latitude} longitude={clinicForm.longitude} onChange={location=>setClinicForm({...clinicForm,...location})}/></div><button className="btn-primary sm:col-span-2">{editClinicId?'Update clinic':'Add clinic'}</button></div></form><div><h3 className="section-title">Clinic management</h3><div className="mt-3 space-y-3">{clinics.map(c=><article className="card" key={c.id}><div className="flex flex-wrap justify-between gap-3"><div><h4 className="font-extrabold">{c.name}</h4><p className="text-sm text-slate-500">{c.address}, {c.city}</p><p className="text-xs text-slate-500">{c.latitude}, {c.longitude}</p></div><div className="flex gap-2"><span className={`badge h-fit ${c.verified?'bg-emerald-50 text-emerald-700':'bg-amber-50 text-amber-700'}`}>{c.verified?'VERIFIED':'PENDING'}</span></div></div><div className="mt-4 flex flex-wrap gap-2"><button className="btn-secondary" onClick={()=>{setEditClinicId(c.id);setClinicForm({...c})}}>Edit clinic</button><button className="btn-secondary" onClick={()=>run(()=>api.patch(`/clinics/${c.id}/verify`,null,{params:{value:!c.verified}}),'Verification updated')}>{c.verified?'Unverify':'Verify'}</button><button className="btn-secondary" onClick={()=>run(()=>api.patch(`/clinics/${c.id}/active`,null,{params:{value:!c.active}}),'Status updated')}>{c.active?'Deactivate':'Activate'}</button><button className="btn-danger" onClick={()=>confirm('Delete clinic?')&&run(()=>api.delete(`/clinics/${c.id}`),'Clinic deleted')}>Delete</button></div></article>)}</div></div></section></div>;
}
